name: jarvis_mobile
description: Jarvis Voice AI Assistant Mobile Client for Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  web_socket_channel: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
